#!/bin/sh

function powermenu {
	options="Cancel\nLog Out\nShutdown\nReboot\nSleep\nLock"
	selected=$(echo -e $options | dmenu -c -bw 5  -l 6 -p "Select: ")
	if [[ $selected = "Shutdown" ]]; then
	    shutdown now
	elif [[ $selected = "Reboot" ]]; then
	     shutdown -r now
	elif [[ $selected = "Sleep" ]]; then
             systemctl suspend
	elif [[ $selected = "Lock" ]]; then
             slock
	elif [[ $selected = "Cancel" ]]; then
             return
	elif [[ $selected = "Log Out" ]]; then
             pkill dwm

	fi
}

powermenu



