#!/bin/sh

function powermenu {
	options="Cancel\nQuit\nShutdown\nRestart\nSleep\nLock"
	selected=$(echo -e $options | dmenu -c -l 6 -p "Select: ")
	if [[ $selected = "Shutdown" ]]; then
	    poweroff
	elif [[ $selected = "Restart" ]]; then
	     reboot
	elif [[ $selected = "Sleep" ]]; then
             systemctl suspend
	elif [[ $selected = "Lock" ]]; then
             slock
	elif [[ $selected = "Cancel" ]]; then
             return
	elif [[ $selected = "Quit" ]]; then
             killall dwm

	fi
}

powermenu



