#!/bin/bash

function wallpaper {
        options="Cancel\nRandom\nCustom"
        selected=$(echo -e $options | dmenu -c -bw 5 -l 3 -p "Select: ")
        if [[ $selected = "Random" ]]; then
             styli.sh -p
        elif [[ $selected = "Custom" ]]; then
             styli.sh -p -d $HOME/github/wallpapers
        elif [[ $selected = "Cancel" ]]; then
             return

        fi
}


wallpaper 

